LongName: Wichita State University ITS and Office of Research
Description: Wichita State University collaboration between ITS and Office of Research
City: Wichita
Country: United States
Latitude: 37.71
Longitude: -97.29
